### ISSUE TITLE
初始化项目失败

### ISSUE THREAD

**Issue by huangliulin** [iqiyi/LiteApp#9]
运行命令初始化项目时报错了, lite-app-init && npm install -d
Error: spawn cp ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by pricelesss** [comment]
能贴一下运行环境吗？

**Comment by huangliulin** [comment]
C:\Users\lin>npm -v
5.6.0

C:\Users\lin>node -v
v8.11.2
还需要什么信息

**Comment by pricelesss** [comment]
在该目录下的完整npm log，谢谢

**Comment by pricelesss** [comment]
The error "spawn cp ENOENT" is caused by child_process.spawn in windows.
now we use exec instead of spawn to fix it.
update liteapp-init to 0.0.2 and try it again.
thx!
